import { Request, Response, NextFunction } from 'express';
import fs from 'fs';
import path from 'path';
import { logger } from '../utils/logger';
import { extractTextFromDocument } from '../utils/documentParser';
import { PerplexityService } from '../utils/perplexityService';
import PDFDocument from 'pdfkit';
import { marked } from 'marked';
import { RequestWithFile } from '../types/documents';

export class DocumentsController {
  private static instance: DocumentsController;
  private perplexityService: PerplexityService;

  private constructor() {
    this.perplexityService = PerplexityService.getInstance();
  }

  public static getInstance(): DocumentsController {
    if (!DocumentsController.instance) {
      DocumentsController.instance = new DocumentsController();
    }
    return DocumentsController.instance;
  }

  public async analyzeDocument(req: RequestWithFile, res: Response, next: NextFunction) {
    try {
      if (!req.file) {
        return res.status(400).json({ error: 'No file uploaded' });
      }

      logger.info(`Processing document: ${req.file.originalname}`);

      // Extract text from the uploaded document
      const text = await extractTextFromDocument(req.file.path, req.file.mimetype);

      // Get summary from Perplexity
      const summary = await this.perplexityService.getDocumentSummary(text);

      // Clean up the uploaded file after processing
      fs.unlinkSync(req.file.path);

      return res.status(200).json(summary);
    } catch (error) {
      logger.error('Error analyzing document:', error);
      next(error);
    }
  }

  public async generatePDF(req: Request, res: Response, next: NextFunction) {
    try {
      const { summary } = req.body;
      if (!summary) {
        return res.status(400).json({ error: 'No summary provided' });
      }

      // Create a new PDF document with margins
      const doc = new PDFDocument({
        margins: {
          top: 60,
          bottom: 60,
          left: 60,
          right: 60,
        },
        size: 'A4',
        info: {
          Title: 'Document Summary',
          Author: 'SmartInvestScout',
          Subject: summary.documentType,
        },
      });

      // Set response headers
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', 'attachment; filename=document-summary.pdf');

      // Pipe the PDF directly to the response
      doc.pipe(res);

      // Define colors (GitHub-inspired)
      const colors = {
        primary: '#0366d6',
        dark: '#24292e',
        gray: '#586069',
        lightGray: '#f6f8fa',
        border: '#e1e4e8',
        heading: '#1b1f23',
        code: '#f6f8fa',
        codeText: '#d73a49',
      };

      // Helper function to check if we need a new page
      const checkPageBreak = (requiredSpace = 50) => {
        if (doc.y + requiredSpace > doc.page.height - doc.page.margins.bottom) {
          doc.addPage();
        }
      };

      // Helper function to add horizontal line
      const addHorizontalLine = (color = colors.border, thickness = 1) => {
        const y = doc.y + 5;
        doc
          .strokeColor(color)
          .lineWidth(thickness)
          .moveTo(doc.page.margins.left, y)
          .lineTo(doc.page.width - doc.page.margins.right, y)
          .stroke();
        doc.moveDown(0.5);
      };

      // Add header with improved styling
      const headerHeight = 80;
      doc.rect(0, 0, doc.page.width, headerHeight).fill(colors.primary);

      // Add title with better positioning
      doc
        .fontSize(28)
        .fillColor('white')
        .text('Document Summary', doc.page.margins.left, 25, {
          align: 'left',
          width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
        });

      // Add subtitle
      doc
        .fontSize(14)
        .fillColor('#e1e4e8')
        .text('Generated by SmartInvestScout', doc.page.margins.left, 55);

      // Set initial position after header
      doc.y = headerHeight + 30;

      // Add document type section with improved styling
      checkPageBreak(60);
      doc.fontSize(18).fillColor(colors.heading).text('Document Type', { underline: false });

      addHorizontalLine();

      doc.fontSize(14).fillColor(colors.dark).text(summary.documentType, { indent: 10 });
      doc.moveDown(2);

      // Parse markdown content
      const tokens = marked.lexer(summary.dynamicSummary);

      // Helper function to render different markdown elements
      const renderToken = (token: any, level = 0) => {
        const indent = level * 20;

        switch (token.type) {
          case 'heading':
            checkPageBreak(40);
            const headingSizes = [24, 20, 18, 16, 14, 12];
            const headingSize = headingSizes[Math.min(token.depth - 1, 5)];

            // Add some space before heading (except h1)
            if (token.depth > 1) {
              doc.moveDown(1.5);
            }

            doc.fontSize(headingSize).fillColor(colors.heading).text(token.text, {
              indent: indent,
              lineGap: 2,
            });

            // Add underline for h1 and h2
            if (token.depth <= 2) {
              addHorizontalLine(
                token.depth === 1 ? colors.dark : colors.border,
                token.depth === 1 ? 2 : 1
              );
            } else {
              doc.moveDown(0.5);
            }
            break;

          case 'paragraph':
            checkPageBreak(30);
            doc.fontSize(12).fillColor(colors.dark).text(token.text, {
              indent: indent,
              lineGap: 3,
              align: 'left',
            });
            doc.moveDown(1);
            break;

          case 'list':
            checkPageBreak(20);
            doc.moveDown(0.5);

            token.items.forEach((item: any, index: number) => {
              checkPageBreak(25);

              const bullet = token.ordered ? `${index + 1}.` : '•';
              const bulletWidth = token.ordered ? 20 : 15;

              // Draw bullet/number
              doc
                .fontSize(12)
                .fillColor(colors.gray)
                .text(bullet, doc.page.margins.left + indent, doc.y, {
                  width: bulletWidth,
                  align: 'right',
                });

              // Draw item text
              doc
                .fontSize(12)
                .fillColor(colors.dark)
                .text(item.text, doc.page.margins.left + indent + bulletWidth + 5, doc.y, {
                  width:
                    doc.page.width -
                    doc.page.margins.right -
                    (doc.page.margins.left + indent + bulletWidth + 5),
                  align: 'left',
                });

              doc.moveDown(1);
            });
            break;

          case 'code':
            checkPageBreak(40);
            doc.moveDown(0.5);

            // Draw code block background
            const codeY = doc.y;
            doc
              .rect(
                doc.page.margins.left + indent,
                codeY,
                doc.page.width - doc.page.margins.right - (doc.page.margins.left + indent),
                20
              )
              .fill(colors.code);

            // Draw code text
            doc
              .fontSize(12)
              .fillColor(colors.codeText)
              .text(token.text, {
                indent: indent + 5,
                align: 'left',
              });

            doc.moveDown(1.5);
            break;

          case 'blockquote':
            checkPageBreak(30);
            doc.moveDown(0.5);

            // Draw quote line
            doc
              .strokeColor(colors.border)
              .lineWidth(2)
              .moveTo(doc.page.margins.left + indent, doc.y)
              .lineTo(doc.page.margins.left + indent, doc.y + 20)
              .stroke();

            // Draw quote text
            doc
              .fontSize(12)
              .fillColor(colors.gray)
              .text(token.text, {
                indent: indent + 10,
                align: 'left',
              });

            doc.moveDown(1.5);
            break;
        }
      };

      // Render all tokens
      tokens.forEach((token) => renderToken(token));

      // Finalize the PDF
      doc.end();
    } catch (error) {
      logger.error('Error generating PDF:', error);
      next(error);
    }
  }
}
